### ISSUE TITLE
Bug in retrieve_tweets

### ISSUE THREAD

**Issue by Nilabhra** [google-research-datasets/recognizing-multimodal-entailment#1]
Please use the variables `id_1` and `id_2` instead of `id1` and `id2` in the two print statements in the `retrieve_tweets` function:
```python
  if len(tweet1[1]) != 1:
    print('Tweet', id1, 'without exactly one image')
```

```python
  if len(tweet2[1]) != 1:
    print('Tweet', id2, 'without exactly one image')
```

**Comment by cesar-ilharco** [comment]
Thank you Nilabhra for pointing this out. Fixed with https://github.com/google-research-datasets/recognizing-multimodal-entailment/commit/8334c7eae574e4a4d43bf1656addd347eab2ec16
