### ISSUE TITLE
GitHub repo of the website

### ISSUE THREAD

**Issue by sayakpaul** [google-research-datasets/recognizing-multimodal-entailment#3]
Hi @cesar-ilharco!

Is there a GitHub repository of the website? 

https://multimodal-entailment.github.io/

We'd love to adapt it for a tutorial we're about to present at ACM KDD this year.

**Comment by multimodal-entailment** [comment]
Hi @sayakpaul 

Yes, this is the repository with the template: https://github.com/multimodal-entailment/multimodal-entailment.github.io

All the best with your presentation at ACM KDD!

**Comment by sayakpaul** [comment]
Thank you.
